version: "3.9"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    networks:
      - mydb
    volumes:
      - database-postgres:/var/lib/postgresql/data

  jerseyhub:
    image: min_jerseyhub
    restart: on-failure
    environment:
      DB_HOST: "postgres"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_PORT: "5432"
      DB_NAME: "postgres"
    depends_on:
      - postgres
    networks:
      - mydb
    ports:
      - "3000:3000"

volumes:
  database-postgres:

networks:
  mydb:
    driver: bridge